### ISSUE TITLE
ALTTP: Got Flute but not in inventory

### ISSUE THREAD

**Issue by Chris8bit** [mcclure/emu-coop#20]
playing ALTTP randomizer and i got the flute but it doesnt give it to my partner, even after he also picked it up. Played another seed. Got the flute, does not show up in either of out inventory.  And yes i checked if it was with the shovel, not there

**Comment by mcclure** [comment]
The randomizer's ram map changed, I have a fix that I'll upload as soon as it's back from the tester. Sorry about that

**Comment by mcclure** [comment]
Fixed with version 1.2 (see releases page or web site). I am sorry that took so long.
