### ISSUE TITLE
coop.lua failing to load on Snes9x

### ISSUE THREAD

**Issue by teh0mega** [mcclure/emu-coop#23]
Attempting to play lttp coop and failing miserably on Windows 10. I tried downloading the pre-zipped snes9x-coop, as well as downloading emu-coop and using it with both snes9x-1.51-rerecording-v7-win32 and snes9x-1.52-rr-r185.

When running any of these versions and loading coop.lua, I get the following error:

error loading module 'iuplua' from file '.\iuplua.dll':
	%1 is not a valid Win32 application.

I have installed a different version of Lua in the past  so I assumed this was some sort of issue, so I built a brand new Win10 VM and got the exact same issue.

Any ideas? Googling hasn't really come up with much.

Thanks!

**Comment by teh0mega** [comment]
Saw the other case with similar issues mentioning it was a issue with missing the VS2015 C++ redistributables. I've attempted to install both the x86 and the x64 versions and both say they are already installed, but they do not show in my Programs and Features list. However, on the VM after installing the redistributables, it works fine.

**Comment by teh0mega** [comment]
After searching for redist issues, I uninstalled 2017 redists and was able to install the 2015 redists. Sorry for bothering you!

**Comment by mcclure** [comment]
Sorry about the confusion! :(
